CREATE TABLE FLIGHT_PASSENGER(
FLIGHT_ID NUMBER NOT NULL,
PASSENGER_ID NUMBER NOT NULL,
PRIMARY KEY(FLIGHT_ID,PASSENGER_ID),
CONSTRAINT FL_PAS_FK1 FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(PAS_ID) ON DELETE CASCADE,
CONSTRAINT FL_PAS_FK2 FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(FLIGHT_ID)ON DELETE CASCADE
)