   CREATE TABLE ITEM_SPRING
   (	ID NUMBER NOT NULL,
   CONSTRAINT ITEM_ID PRIMARY KEY(ID),
   NAME VARCHAR2(10) NOT NULL,
   DATE_CREATED DATE,
   LAST_UPDATED_DATE DATE,
   DESCRIPTION NVARCHAR2(30) NOT NULL);